name: slider_slider
description: A customizable Flutter carousel slider with drag gestures, custom image widgets, and optional questions/answers.
version: 1.0.0
homepage: https://github.com/shahzadkhan1998/slider_custom
repository: https://github.com/shahzadkhan1998/slider_custom
issue_tracker: https://github.com/shahzadkhan1998/slider_custom/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0